import React, { useEffect, useState } from 'react';
import { useFilters } from '../context/FilterContext';
import { fetchPricingMetrics } from '../services/api';
import KpiCard from '../components/KpiCard';
import ChartHeader from '../components/ChartHeader';
import SkeletonLoader from '../components/SkeletonLoader';
import EmptyState from '../components/EmptyState';
import { 
  DollarSign, Sun, TrendingUp, Tag, BarChart2, LineChart as LineIcon, 
  Layers, PieChart as PieIcon
} from 'lucide-react';
import { 
  BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, ResponsiveContainer, 
  XAxis, YAxis, Tooltip, Legend, CartesianGrid 
} from 'recharts';

const ROOM_COLORS = ['#3B82F6', '#10B981', '#8B5CF6', '#F59E0B'];
const TIER_COLORS = ['#3B82F6', '#10B981', '#F59E0B'];

const DynamicPricingDashboard = () => {
  const { filters } = useFilters();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const load = async () => {
      setLoading(true);
      try {
        const res = await fetchPricingMetrics(filters);
        setData(res.data);
      } catch (err) {
        console.error('Failed to load pricing metrics:', err);
      } finally {
        setLoading(false);
      }
    };
    load();
  }, [filters]);

  if (loading) return <SkeletonLoader type="full" />;
  if (!data || !data.kpiSummary) return <EmptyState city={filters.city} month={filters.month} />;

  const { 
    kpiSummary, 
    priceByRoomType, 
    seasonalPricingTrends, 
    weekendVsWeekday, 
    pricingTierContribution 
  } = data;

  return (
    <div className="space-y-7 animate-fade-in w-full pb-8">
      {/* 1. Primary Hotel Revenue KPI Grid (4 Cards) */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
        <KpiCard 
          title="Average Room Price" 
          value={`₹${kpiSummary.avgRoomPrice.toLocaleString()}`} 
          change={5.2} 
          icon={DollarSign} 
        />
        <KpiCard 
          title="Highest Seasonal Price" 
          value={`₹${kpiSummary.highestSeasonalPrice.toLocaleString()}`} 
          subtitle="Peak Season Surge"
          icon={Sun} 
        />
        <KpiCard 
          title="Weekend Revenue Increase" 
          value={`+${kpiSummary.weekendRevenueIncrease}%`} 
          change={4.8} 
          icon={TrendingUp} 
        />
        <KpiCard 
          title="Revenue from Pricing Rules" 
          value={`₹${kpiSummary.pricingStrategyRevenue} Lakhs`} 
          subtitle="Strategy Contribution" 
          icon={Tag} 
        />
      </div>

      {/* 2. Chart Grid 1: Average Room Price by Room Type & Revenue Contribution by Pricing Tier */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 w-full">
        {/* Chart 1: Average Room Price by Room Type (Bar Chart) */}
        <div className="bg-[#0E1422] border border-[#1E293B] rounded-[12px] p-6 h-[390px] flex flex-col justify-between shadow-md w-full">
          <ChartHeader 
            title="Average Room Price by Room Type (₹)" 
            subtitle="Comparing nightly room rates to identify premium pricing opportunities"
            unitBadge="Room Price (₹)"
            statusBadge="Price Rank"
            icon={BarChart2}
          />
          <div className="flex-1 w-full mt-2">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={priceByRoomType} margin={{ top: 15, right: 20, left: 20, bottom: 20 }}>
                <CartesianGrid stroke="rgba(255,255,255,0.06)" vertical={false} />
                <XAxis dataKey="room_type" stroke="#6B7280" fontSize={12} tickLine={false} tickMargin={10} />
                <YAxis stroke="#6B7280" fontSize={12} tickLine={false} width={70} tickFormatter={(v) => `₹${v}`} />
                <Tooltip 
                  contentStyle={{ backgroundColor: '#0B101D', borderColor: 'rgba(255,255,255,0.15)', borderRadius: '8px', color: '#fff' }} 
                  formatter={(val) => [`₹${val.toLocaleString()}`, 'Avg Price']}
                />
                <Bar dataKey="avgPrice" radius={[6, 6, 0, 0]}>
                  {priceByRoomType.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={ROOM_COLORS[index % ROOM_COLORS.length]} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Chart 4: Revenue Contribution by Pricing Tier (Donut Chart & Progress Bars) */}
        <div className="bg-[#0E1422] border border-[#1E293B] rounded-[12px] p-6 h-[390px] flex flex-col justify-between shadow-md w-full">
          <ChartHeader 
            title="Revenue Contribution by Pricing Tier" 
            subtitle="Proportional revenue generated by base rates vs weekend vs festival pricing"
            unitBadge="Revenue Share (%)"
            statusBadge="Pricing Mix"
            icon={PieIcon}
          />
          
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 items-center flex-1 mt-2">
            {/* Donut Chart */}
            <div className="h-[220px] w-full">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie 
                    data={pricingTierContribution} 
                    dataKey="share" 
                    nameKey="tier" 
                    cx="50%" 
                    cy="50%" 
                    innerRadius={55} 
                    outerRadius={85} 
                    paddingAngle={4}
                  >
                    {pricingTierContribution.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color || TIER_COLORS[index % TIER_COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip 
                    contentStyle={{ backgroundColor: '#0B101D', borderColor: 'rgba(255,255,255,0.15)', borderRadius: '8px', color: '#fff' }} 
                    formatter={(val) => [`${val}%`, 'Revenue Share']}
                  />
                </PieChart>
              </ResponsiveContainer>
            </div>

            {/* Tier Legend & Progress Bars */}
            <div className="space-y-3 pr-2">
              {pricingTierContribution.map((tier, idx) => (
                <div key={idx} className="space-y-1.5 bg-[#070A12] p-3 rounded-lg border border-[#1E293B]">
                  <div className="flex justify-between text-xs font-bold text-slate-200">
                    <span className="flex items-center gap-2">
                      <span className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: tier.color || TIER_COLORS[idx] }}></span>
                      {tier.tier}
                    </span>
                    <span className="text-white font-extrabold">{tier.share}%</span>
                  </div>
                  <div className="w-full h-2 rounded-full bg-slate-900 overflow-hidden">
                    <div 
                      className="h-full rounded-full transition-all duration-300"
                      style={{ width: `${tier.share}%`, backgroundColor: tier.color || TIER_COLORS[idx] }}
                    ></div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* 3. Chart Grid 2: Seasonal Pricing Trends & Weekend vs Weekday Pricing Analytics */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 w-full">
        {/* Chart 2: Seasonal Pricing Trends (Line Chart) */}
        <div className="bg-[#0E1422] border border-[#1E293B] rounded-[12px] p-6 h-[390px] flex flex-col justify-between shadow-md w-full">
          <ChartHeader 
            title="Seasonal Pricing & Occupancy Trends" 
            subtitle="Comparing average prices and occupancy rates across seasonal periods"
            unitBadge="Seasonal Metrics"
            statusBadge="Seasonality"
            icon={LineIcon}
          />
          <div className="flex-1 w-full mt-2">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={seasonalPricingTrends} margin={{ top: 15, right: 20, left: 20, bottom: 20 }}>
                <CartesianGrid stroke="rgba(255,255,255,0.06)" vertical={false} />
                <XAxis dataKey="season" stroke="#6B7280" fontSize={12} tickLine={false} tickMargin={10} />
                <YAxis yAxisId="left" stroke="#6B7280" fontSize={12} tickLine={false} width={70} tickFormatter={(v) => `₹${v}`} />
                <YAxis yAxisId="right" orientation="right" stroke="#10B981" fontSize={12} tickLine={false} width={50} unit="%" />
                <Tooltip 
                  contentStyle={{ backgroundColor: '#0B101D', borderColor: 'rgba(255,255,255,0.15)', borderRadius: '8px', color: '#fff' }} 
                />
                <Legend verticalAlign="top" height={36} iconType="circle" />
                <Line yAxisId="left" type="monotone" name="Avg Price (₹)" dataKey="avgPrice" stroke="#3B82F6" strokeWidth={3} dot={{ r: 5, fill: '#3B82F6' }} />
                <Line yAxisId="right" type="monotone" name="Occupancy (%)" dataKey="occupancy" stroke="#10B981" strokeWidth={3} dot={{ r: 5, fill: '#10B981' }} />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Chart 3: Weekend vs Weekday Pricing Analytics (Grouped Bar Chart) */}
        <div className="bg-[#0E1422] border border-[#1E293B] rounded-[12px] p-6 h-[390px] flex flex-col justify-between shadow-md w-full">
          <ChartHeader 
            title="Weekend vs Weekday Pricing Analytics" 
            subtitle="Comparing weekday vs weekend pricing rates across room categories"
            unitBadge="Price Comparison"
            statusBadge="Surge Analysis"
            icon={Layers}
          />
          <div className="flex-1 w-full mt-2">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={weekendVsWeekday} margin={{ top: 15, right: 20, left: 20, bottom: 20 }}>
                <CartesianGrid stroke="rgba(255,255,255,0.06)" vertical={false} />
                <XAxis dataKey="room_type" stroke="#6B7280" fontSize={12} tickLine={false} tickMargin={10} />
                <YAxis stroke="#6B7280" fontSize={12} tickLine={false} width={70} tickFormatter={(v) => `₹${v}`} />
                <Tooltip 
                  contentStyle={{ backgroundColor: '#0B101D', borderColor: 'rgba(255,255,255,0.15)', borderRadius: '8px', color: '#fff' }} 
                  formatter={(val) => [`₹${val.toLocaleString()}`]}
                />
                <Legend verticalAlign="top" height={36} iconType="circle" />
                <Bar name="Weekday Price (₹)" dataKey="weekdayPrice" fill="#6366F1" radius={[4, 4, 0, 0]} />
                <Bar name="Weekend Price (₹)" dataKey="weekendPrice" fill="#10B981" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DynamicPricingDashboard;
